# -*- coding: utf-8 -*-
"""DistilBERT finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1En97V_vBa8nhJ776AK__kOr6RdM5FAAU

# Data Preprocessing
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Final_merged_reduced_intents_cleaned_153k_v15.csv")
df.head()

for i,intents in enumerate(df['intents'].unique(),start=1):
  print(i,".",intents)

df.shape

(153460, 2)

import pandas as pd

intent_counts = df['intents'].value_counts()
print("Intents with the least instructions (top 10):")
print(intent_counts.head(20))

"""### Distribution of Intents

Let's visualize the distribution of the `intents` column to see the frequency of each class. This is important for understanding potential class imbalance issues.
"""

plt.figure(figsize=(15, 15))
sns.countplot(y='intents', data=df, order=df['intents'].value_counts().index, palette='viridis')
plt.title('Distribution of Intents')
plt.xlabel('Count')
plt.ylabel('Intent')
plt.show()

df['intents'].unique()

df['intents'].nunique()

import pandas as pd

# Step 1: Load your CSV file
df = pd.read_csv("/content/merged_cleaned_100k_v11.csv")  # replace with your CSV file path

# Specify the intent
target_intent = "remove_from_cart"

# Filter instructions for that intent
instructions_only = df[df['intents'] == target_intent]['instructions']

# Optional: Convert to a list
instructions_list = instructions_only.tolist()

# Print the instructions
for i, instr in enumerate(instructions_list, 1):
    print(f"{i}. {instr}")

# Remove rows with the "change_order" intent
df_filtered = df[df['intents'] != "change_order"]

# Save the updated dataset to a new CSV (or overwrite the existing one)
df_filtered.to_csv("dataset_without_change_order_v10.csv", index=False)

print("change_order intent has been removed. Updated dataset saved!")

print(df_filtered.shape)
print(df_filtered['intents'].nunique())

"""#Model Training"""

!pip install transformers datasets scikit-learn pandas torch

# =========================
# 1. IMPORT LIBRARIES
# =========================
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
import random

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score

from datasets import Dataset
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback
)

# =========================
# 2. SET SEED
# =========================
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

# =========================
# 3. LOAD DATASET
# =========================
df = pd.read_csv("/content/Final_merged_reduced_intents_cleaned_153k_v15.csv")

# =========================
# 4. CLEANING
# =========================
df = df.dropna(subset=["instructions", "intents"])
df = df[df["instructions"].str.strip() != ""]
df = df.drop_duplicates()
df["instructions"] = df["instructions"].str.strip()

print("Dataset size:", len(df))

# =========================
# 5. LABEL ENCODING
# =========================
label_encoder = LabelEncoder()
df["label"] = label_encoder.fit_transform(df["intents"])
num_labels = len(label_encoder.classes_)

print("Number of classes:", num_labels)

# =========================
# 6. TRAIN / VAL / TEST SPLIT (70/15/15)
# =========================
train_df, temp_df = train_test_split(
    df,
    test_size=0.3,
    stratify=df["label"],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    stratify=temp_df["label"],
    random_state=42
)

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

# =========================
# 7. CONVERT TO HF DATASET
# =========================
train_dataset = Dataset.from_pandas(train_df.reset_index(drop=True))
val_dataset = Dataset.from_pandas(val_df.reset_index(drop=True))
test_dataset = Dataset.from_pandas(test_df.reset_index(drop=True))

# Remove unused columns
columns_to_remove = [col for col in train_dataset.column_names if col not in ["instructions", "label"]]
train_dataset = train_dataset.remove_columns(columns_to_remove)
val_dataset = val_dataset.remove_columns(columns_to_remove)
test_dataset = test_dataset.remove_columns(columns_to_remove)

# =========================
# 8. TOKENIZER
# =========================
tokenizer = DistilBertTokenizerFast.from_pretrained(
    "distilbert-base-uncased"
)

def tokenize(batch):
    return tokenizer(
        batch["instructions"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
val_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
test_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])

# =========================
# 9. LOAD MODEL
# =========================
model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=num_labels
)

id2label = {i: label for i, label in enumerate(label_encoder.classes_)}
label2id = {label: i for i, label in enumerate(label_encoder.classes_)}

model.config.id2label = id2label
model.config.label2id = label2id

# =========================
# 10. METRICS (TOP-1 + TOP-2)
# =========================
def compute_metrics(eval_pred):
    logits, labels = eval_pred

    # Convert logits → softmax probabilities
    probs = torch.tensor(logits)
    probs = F.softmax(probs, dim=1)

    # Top-1 predictions
    top1_preds = torch.argmax(probs, dim=1).numpy()

    # Top-2 predictions
    top2_preds = torch.topk(probs, k=2, dim=1).indices.numpy()

    # Top-1 Accuracy
    top1_accuracy = accuracy_score(labels, top1_preds)

    # Top-2 Accuracy
    top2_correct = sum(
        label in top2
        for label, top2 in zip(labels, top2_preds)
    )
    top2_accuracy = top2_correct / len(labels)

    # F1 (Top-1 based)
    f1_weighted = f1_score(labels, top1_preds, average="weighted")

    return {
        "top1_accuracy": top1_accuracy,
        "top2_accuracy": top2_accuracy,
        "f1_weighted": f1_weighted
    }

# =========================
# 11. TRAINING ARGUMENTS
# =========================
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1_weighted",
    greater_is_better=True,
    num_train_epochs=8,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    logging_dir="./logs",
    save_total_limit=2,
    fp16=torch.cuda.is_available(),
    seed=42
)

# =========================
# 12. TRAINER
# =========================
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

# =========================
# 13. TRAIN
# =========================
trainer.train()

# =========================
# 14. FINAL TEST EVALUATION
# =========================
print("\nFinal Test Evaluation:")
test_results = trainer.evaluate(test_dataset)
print(test_results)

## Training and validation Loss graph

import matplotlib.pyplot as plt
import pandas as pd

# Convert log history to DataFrame
logs = pd.DataFrame(trainer.state.log_history)

# Extract training and validation logs
train_logs = logs[logs["loss"].notna()]
eval_logs = logs[logs["eval_loss"].notna()]

# Plot Training Loss
plt.figure()
plt.plot(train_logs["epoch"], train_logs["loss"])
plt.xlabel("Epoch")
plt.ylabel("Training Loss")
plt.title("Training Loss vs Epoch")
plt.show()

# Plot Validation Loss
plt.figure()
plt.plot(eval_logs["epoch"], eval_logs["eval_loss"])
plt.xlabel("Epoch")
plt.ylabel("Validation Loss")
plt.title("Validation Loss vs Epoch")
plt.show()

# Plot Top-1 Accuracy
plt.figure()
plt.plot(eval_logs["epoch"], eval_logs["eval_top1_accuracy"])
plt.xlabel("Epoch")
plt.ylabel("Top-1 Accuracy")
plt.title("Validation Top-1 Accuracy vs Epoch")
plt.show()

# Plot Top-2 Accuracy
plt.figure()
plt.plot(eval_logs["epoch"], eval_logs["eval_top2_accuracy"])
plt.xlabel("Epoch")
plt.ylabel("Top-2 Accuracy")
plt.title("Validation Top-2 Accuracy vs Epoch")
plt.show()

# Save final trained model
trainer.save_model("final_production_model")

# Save tokenizer
tokenizer.save_pretrained("final_production_model")

print("Model saved successfully ✅")

# Shows model's total size
import os

def folder_size(path="."):
    total = 0
    for dirpath, dirnames, filenames in os.walk(path):
        for f in filenames:
            fp = os.path.join(dirpath, f)
            total += os.path.getsize(fp)
    return total

size_bytes = folder_size("final_production_model")
print(f"Model size on disk: {size_bytes/1e6:.2f} MB")

# Shows model's total parameters
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("final_production_model")

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params/1e6:.2f} M")

## Manual Prediction Function

import torch
import torch.nn.functional as F

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

model.eval()

def predict_intent(text, top_k=2):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=128
    )

    # Move inputs to same device as model
    inputs = {key: value.to(device) for key, value in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits

        probs = F.softmax(logits, dim=1)
        topk_probs, topk_indices = torch.topk(probs, k=top_k, dim=1)

    topk_probs = topk_probs[0].cpu().numpy()
    topk_indices = topk_indices[0].cpu().numpy()

    intents = label_encoder.inverse_transform(topk_indices)

    return list(zip(intents, topk_probs))


print(predict_intent("I  wsnto get the realme c34"))

# Save model in local system

import shutil
from google.colab import files

# 1️⃣ Zip the folder
shutil.make_archive("/content/final_production_model", 'zip', "/content/final_production_model")

# 2️⃣ Download the zip
files.download("/content/final_production_model.zip")



!pip freeze > requirements.txt

